arguments = [
    ("CBV", "FBV"),
    ("Linux", "Mac OS X"),
    ("Emacs", "Vim"),
    ("Semi-colons", "No semi-colons"),
    ("Mac", "PC"),
    ("Consoles", "PC"),
    ("Angular", "Backbone"),
    ("Ruby on Rails", "Django"),
    ("PHP", "Anything else"),
    ("Feature switching", "Branching"),
    ("Meetings", "Doing actual work"),
    ("IDE", "Text Editor"),
    ("iOS", "Android"),
    ("XBox", "PlayStation"),
    ("Compiled", "Interpreted"),
    ("Spaces", "Tabs"),
    ("Photoshop", "Gimp"),
    ("CLI", "GUI"),
    ("XML", "JSON"),
    ("INI", "YAML"),
    ("CoffeeScript", "JavaScript"),
    ("NoSQL", "SQL"),
    ("MySQL", "Postgres"),
    ("Pronounced OS eks", "Pronounced OS ten"),
    ("Pronounced gif", "Pronounced gif"),
    ("Top posting", "Bottom posting"),
    ("SysV", "BSD"),
    ("Sun OS", "Solaris"),
    ("Carbon", "Cocoa"),
    ("Sockets", "Streams"),
    ("IPv4", "IPv6"),
    ("REST", "SOAP"),
    ("ASCII", "EBCDIC"),
    ("Little endian", "Big endian"),
    ("PowerPC", "Intel"),
    ("nVidia", "ATI"),
    ("OpenGL", "DirectX"),
    ("Git", "Mercurial"),
    ("Native", "Web"),
    ("BSD KNF Style", "Allman Style"),
    ("FP", "OOP"),
    ("Java", "C++"),
    ("Python", "Ruby"),
    ("Zsh", "Bash"),
    ("LESS", "SASS"),
    ("jQuery animations", "CSS Animations"),
    ("Boolean", "boolean"),
    ("DHH", "TDD"),
    ("Swift", "Objective C"),
    ("Grunt", "Gulp"),
    ("Flask", "Bottle"),
    ("MIT", "GPL"),
    ("Inverted", "Non-inverted mouse"),
    ("Marvel", "DC"),
    ("Star Wars", "Star Trek"),
    ("ORMs", "Raw SQL"),
    ("Angular", "React"),
    ("Batman", "Superman"),
    ("Code", "Sleep"),
    ("Morrowind", "Skyrim"),
    ("Covariance", "Contravariance"),
    ("Java", "C#"),
    ("Zed Shaw", "Python 3"),
    ("Python 2", "Python 3"),
    ("Vue", "React"),
    ("Replicant", "Not a replicant"),
    ("AWS", "Google Cloud Platform"),
    ("Slack", "Discord"),
    ("Rich models", "Anemic models"),
    ("Symfony", "Laravel"),
    ("Monolith", "Microservices"),
    ("HOC", "Render props"),
    ("Hooks", "Life cycle methods"),
    ("Auth0", "Cognito"),
    ("Operator Mono Medium Italic", "Regular mono font"),
    ("!!", "Boolean"),
    ("Class components", "Functional components"),
    ("Black", "YAPF"),
    ("Spotify", "Apple Music"),
    ("Bose QC35 II", "Sony WH-1000XM3"),
    ("Your RAM", "Electron app"),
    ("'", '"'),
    ("Look Before You Leap", "Easier to Ask For Forgiveness Than Permission"),
    ("Selenium", "Cypress"),
]
